"""Main LLM Wiki Engine — orchestrates ingest, synthesize, lint cycle.

The engine is the thin coordinator between:
  - `Ingester` (source normalization, no LLM)
  - `Synthesizer` (Claude Haiku writes / merges)
  - optional quality engines (contradiction + staleness) — imported
    lazily because they're owned by another agent and may not exist
    yet at import time.

Loading the vault is eager on first use and cached on `self._pages` so
repeated ingest calls don't re-walk the filesystem. Callers that need
a fresh read (for example, after an external Obsidian edit) should
invoke `load_vault()` explicitly.
"""

from __future__ import annotations

import logging
from collections import Counter
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from .ingester import Ingester, Source, SourceType
from .synthesizer import SynthesisDecision, Synthesizer, WikiPage

logger = logging.getLogger("aegis.wiki")

# Marker that `update_overview` preserves — anything above it is human
# prose, anything below is regenerated by the LLM. This lets a human
# own the introduction while the engine owns the service index.
OVERVIEW_MARKER = "<!-- AUTO-GENERATED BELOW -->"

_PAGE_TYPE_DIRS: tuple[str, ...] = ("entities", "concepts", "incidents", "runbooks")


class WikiEngineConfig(BaseModel):
    """Runtime configuration for the wiki engine.

    `stale_threshold_days` / `archive_threshold_days` are defaults for
    the staleness engine; the engine reads them at lint time rather
    than at init so the values can be tuned without a restart.
    """

    vault_root: Path = Field(
        default_factory=lambda: Path("~/Documents/obsidian-sre").expanduser()
    )
    stale_threshold_days: int = 30
    archive_threshold_days: int = 180
    synthesis_model: str = "claude-haiku-4-5-20251001"
    contradiction_model: str = "claude-sonnet-4-6"

    model_config = {"arbitrary_types_allowed": True}


class WikiEngine:
    """Top-level coordinator for wiki ingest + maintenance.

    Holds a reference to the AsyncAnthropic client and the vault state.
    The quality engines (contradiction, staleness) are optional deps:
    if their modules aren't importable, the engine still works for
    ingest/synthesis and reports 'unavailable' in `health_status`.
    """

    def __init__(
        self, config: WikiEngineConfig, anthropic_client: Any
    ) -> None:
        """Wire up the subcomponents and probe for optional engines.

        We probe-import contradiction/staleness lazily because another
        agent owns those files and they may land after this module. If
        import fails, the corresponding attribute is None and the API
        routers will surface 'feature unavailable' rather than crash.
        """

        self.config = config
        self.client = anthropic_client
        self.ingester = Ingester()
        self.synthesizer = Synthesizer(
            anthropic_client=anthropic_client, model=config.synthesis_model
        )
        self._pages: list[WikiPage] | None = None
        self._pages_by_slug: dict[str, WikiPage] = {}

        self.contradiction_detector: Any = None
        self.staleness_linter: Any = None
        try:  # pragma: no cover - optional dependency wiring
            from .contradiction import ContradictionDetector  # type: ignore

            self.contradiction_detector = ContradictionDetector(
                anthropic_client=anthropic_client,
                model=config.contradiction_model,
            )
        except Exception as exc:  # noqa: BLE001
            logger.debug("contradiction engine unavailable: %s", exc)

        try:  # pragma: no cover - optional dependency wiring
            from .staleness import StalenessLinter  # type: ignore

            self.staleness_linter = StalenessLinter(
                stale_after_days=config.stale_threshold_days,
                archive_after_days=config.archive_threshold_days,
            )
        except Exception as exc:  # noqa: BLE001
            logger.debug("staleness engine unavailable: %s", exc)

    # -- Primary ingest -------------------------------------------------

    async def ingest(self, source_path: Path | str) -> WikiPage:
        """Full ingest cycle for a single source.

        Steps: normalize → load vault → LLM routing → LLM write → save.
        The returned page is already persisted to disk; callers don't
        need to call `.save()` themselves.
        """

        if isinstance(source_path, (str, Path)) and not isinstance(
            source_path, Source
        ):
            source = await self.ingester.ingest_file(Path(source_path))
        else:  # pragma: no cover - defensive; API passes paths
            source = source_path  # type: ignore[assignment]

        pages = await self.load_vault()
        decision: SynthesisDecision = await self.synthesizer.decide_action(
            source=source, existing_pages=pages
        )
        logger.info(
            "synthesis decision: action=%s target=%s reason=%s",
            decision.action,
            decision.target_page_slug,
            decision.reasoning[:120],
        )

        if decision.action == "skip":
            # Return a lightweight placeholder so callers can report why.
            return WikiPage(
                title=f"[skipped] {Path(source.path_or_url).name}",
                type="concept",
                slug=f"skipped-{source.id}",
                path=self.config.vault_root / "skipped" / f"{source.id}.md",
                frontmatter={"skipped": True, "reason": decision.reasoning},
                body=decision.reasoning,
                sources=[source.path_or_url],
            )

        if decision.action == "update_existing" and decision.target_page_slug:
            target = self.get_page_by_slug(decision.target_page_slug)
            if target is None:
                logger.warning(
                    "router chose update_existing but slug %r not found; "
                    "falling back to create_new",
                    decision.target_page_slug,
                )
                decision = SynthesisDecision(
                    action="create_new",
                    target_type=decision.target_type or "concept",
                    reasoning=decision.reasoning,
                )
            else:
                merged = await self.synthesizer.merge_into_page(source, target)
                path = merged.save(self.config.vault_root)
                merged.path = path
                self._pages_by_slug[merged.slug] = merged
                return merged

        # create_new path (also reached via fallback above)
        page_type = decision.target_type or _default_type_for(source)
        new_page = await self.synthesizer.synthesize_new_page(source, page_type)
        path = new_page.save(self.config.vault_root)
        new_page.path = path
        if self._pages is None:
            self._pages = []
        self._pages.append(new_page)
        self._pages_by_slug[new_page.slug] = new_page
        return new_page

    # -- Vault IO -------------------------------------------------------

    async def load_vault(self) -> list[WikiPage]:
        """Walk the vault directory and hydrate every .md file.

        Pages that fail to parse are logged and skipped rather than
        aborting the whole load — a single malformed file should not
        take down synthesis for the other 99.
        """

        pages: list[WikiPage] = []
        by_slug: dict[str, WikiPage] = {}
        vault_root = self.config.vault_root

        for type_dir in _PAGE_TYPE_DIRS:
            dir_path = vault_root / type_dir
            if not dir_path.is_dir():
                continue
            for md_path in dir_path.glob("*.md"):
                try:
                    page = WikiPage.from_file(md_path)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("failed to load %s: %s", md_path, exc)
                    continue
                pages.append(page)
                by_slug[page.slug] = page

        self._pages = pages
        self._pages_by_slug = by_slug
        logger.info(
            "loaded %d pages from vault %s", len(pages), vault_root
        )
        return pages

    def get_page_by_slug(self, slug: str) -> WikiPage | None:
        """Return the in-memory page for `slug`, or None.

        Requires `load_vault` has been called at least once; ingest()
        always does this, so callers using only ingest don't need to
        worry about bootstrapping.
        """

        return self._pages_by_slug.get(slug)

    # -- Overview page --------------------------------------------------

    async def update_overview(self) -> WikiPage:
        """Regenerate the vault overview page.

        Preserves everything above `OVERVIEW_MARKER` and replaces
        everything below with a Haiku-generated services table, recent
        incidents list, and cross-cutting patterns section. Written to
        `<vault_root>/overview.md` with type='concept' and slug='overview'.
        """

        pages = await self.load_vault()
        overview_path = self.config.vault_root / "overview.md"

        # Preserve human-authored prefix if the marker exists.
        preamble = "# SRE Knowledge Vault\n\n"
        if overview_path.exists():
            existing = overview_path.read_text(encoding="utf-8")
            if OVERVIEW_MARKER in existing:
                preamble = existing.split(OVERVIEW_MARKER)[0].rstrip() + "\n\n"

        # Build a compact index for the LLM — title/slug/type/summary only.
        index_lines: list[str] = []
        for p in pages:
            first_line = (p.body or "").strip().splitlines()[:1]
            summary = (first_line[0] if first_line else "").strip()[:200]
            index_lines.append(
                f"- [[{p.slug}|{p.title}]] ({p.type}, updated "
                f"{p.last_updated.date().isoformat()}): {summary}"
            )
        index_block = "\n".join(index_lines) or "(vault is empty)"

        user_prompt = (
            "Write the auto-generated section of the SRE vault overview. "
            "Output pure markdown (no frontmatter, no preamble). Include "
            "exactly these three sections in order:\n"
            "  ## Services\n"
            "  ## Recent incidents\n"
            "  ## Cross-cutting patterns\n\n"
            "The Services section must be a markdown table with columns "
            "Service | Type | Last updated | Link (using [[slug]] syntax).\n"
            "Recent incidents: bulleted list of the most recent 'incident' "
            "pages, sorted by last_updated descending, most recent first.\n"
            "Cross-cutting patterns: 3-6 bullets summarizing themes observed "
            "across pages (e.g. recurring root causes, shared dependencies). "
            "Only use [[WikiLinks]] to pages that appear in the index.\n\n"
            f"VAULT INDEX ({len(pages)} pages):\n{index_block}\n"
        )

        # Use the synthesizer's Haiku call directly so we get cost tracking.
        generated = await self.synthesizer._call(  # noqa: SLF001
            system=self.synthesizer._SYSTEM_PROMPT,  # noqa: SLF001
            user=user_prompt,
            max_tokens=3072,
        )

        final_body = f"{preamble}{OVERVIEW_MARKER}\n\n{generated.strip()}\n"
        now = datetime.now(UTC)
        page = WikiPage(
            title="SRE Knowledge Vault",
            type="concept",
            slug="overview",
            path=overview_path,
            frontmatter={
                "title": "SRE Knowledge Vault",
                "type": "concept",
                "slug": "overview",
                "auto_generated": True,
                "last_updated": now.isoformat(),
                "freshness": "current",
            },
            body=final_body,
            last_updated=now,
            sources=[],
            freshness="current",
        )

        # Overview lives at vault root, not in a type-dir, so write directly.
        overview_path.parent.mkdir(parents=True, exist_ok=True)
        overview_path.write_text(page.to_markdown(), encoding="utf-8")
        self._pages_by_slug[page.slug] = page
        return page

    # -- Health ---------------------------------------------------------

    def health_status(self) -> dict[str, Any]:
        """Return a snapshot of vault health for the dashboard.

        Non-blocking: reads cached `self._pages` if populated, else
        reports `loaded: false`. This method is sync on purpose so the
        FastAPI `/health` style endpoints don't need to await.
        """

        pages = self._pages or []
        freshness_counts = Counter(p.freshness for p in pages)
        type_counts = Counter(p.type for p in pages)

        last_updated_iso: str | None = None
        if pages:
            latest = max(p.last_updated for p in pages)
            last_updated_iso = latest.isoformat()

        stale_threshold = datetime.now(UTC) - timedelta(
            days=self.config.stale_threshold_days
        )
        inferred_stale = sum(
            1 for p in pages if p.last_updated < stale_threshold
        )

        return {
            "vault_root": str(self.config.vault_root),
            "loaded": self._pages is not None,
            "total_pages": len(pages),
            "by_type": dict(type_counts),
            "by_freshness": dict(freshness_counts),
            "inferred_stale_count": inferred_stale,
            "last_updated": last_updated_iso,
            "models": {
                "synthesis": self.config.synthesis_model,
                "contradiction": self.config.contradiction_model,
            },
            "optional_engines": {
                "contradiction": self.contradiction_detector is not None,
                "staleness": self.staleness_linter is not None,
            },
            "cost_tracking": {
                "calls": len(self.synthesizer.all_usage),
                "total_cost_usd": round(
                    sum(u.cost_usd for u in self.synthesizer.all_usage), 6
                ),
            },
        }


def _default_type_for(source: Source) -> str:
    """Map a SourceType to a reasonable default page type.

    Used only when the LLM router fails to supply a target_type — most
    of the time Haiku returns one explicitly, so this is a safety net.
    """

    if source.type == SourceType.SIGNOZ_INCIDENT:
        return "incident"
    if source.type == SourceType.CONFLUENCE_PAGE:
        return "concept"
    return "concept"
